apiVersion: apps/v1
kind: Deployment
metadata:
  name: top10-books-deployment
  labels:
    app: top10-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top10-books
  template:
    metadata:
      labels:
        app: top10-books
    spec:
      containers:
      - name: top10-books
        image: $registry/book_app:v1 # github actions create image
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: top10-books-svc
spec:
  type: NodePort
  selector:
    app: top10-books
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
 